### ISSUE TITLE
请问能否增加多语言的人声支持？

### ISSUE THREAD

**Issue by Nicolas-Gong** [WhiteMagic2014/tts-edge-java#5]
en-US-AvaMultilingualNeural
en-US-AndrewMultilingualNeural
en-US-EmmaMultilingualNeural
en-US-BrianMultilingualNeural
De-DE-FlorianMultilingualNeural
De-DE-SeraphinaMultilingualNeural
Fr-FR-RemyMultilingualNeural
Fr-FR-VivienneMultilingualNeural
zh-CN-XiaoxiaoMultilingualNeural

https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/9-more-realistic-ai-voices-for-conversations-now-generally/ba-p/4099471

新增了9个人声，其中zh-CN-XiaoxiaoMultilingualNeural这个edge没有开放，其他的都开放了，不知道大佬能否在项目中增加这些人声？

**Comment by WhiteMagic2014** [comment]
感谢提醒 1.2.1版本更新了如下17个声音
    en-US-AvaMultilingualNeural
    en-US-AndrewMultilingualNeural
    en-US-EmmaMultilingualNeural
    en-US-BrianMultilingualNeural
    en-US-AvaNeural
    en-US-AndrewNeural
    en-US-EmmaNeural
    en-US-BrianNeural
    fr-CA-ThierryNeural
    fr-FR-VivienneMultilingualNeural
    fr-FR-RemyMultilingualNeural
    de-DE-SeraphinaMultilingualNeural
    de-DE-FlorianMultilingualNeural
    it-IT-GiuseppeNeural
    ko-KR-HyunsuNeural
    pt-BR-ThalitaNeural
    es-ES-XimenaNeural

**Comment by RXlung** [comment]
![image](https://github.com/user-attachments/assets/24d9d1be-dad8-40f2-8488-9e8aaeb060c3)
有晓梦这个人吗？

**Comment by WhiteMagic2014** [comment]
> ![image](https://private-user-images.githubusercontent.com/21995371/357716929-24d9d1be-dad8-40f2-8488-9e8aaeb060c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NzUzODUsIm5iZiI6MTcyMzc3NTA4NSwicGF0aCI6Ii8yMTk5NTM3MS8zNTc3MTY5MjktMjRkOWQxYmUtZGFkOC00MGYyLTg0ODgtOWU4YWFlYjA2MGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDAyMjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYzI3ZmZkMzIyNmQzMGM3YjFlMjFlOGRjOGM1NjYwZmVjZjEyMzI1MDY1M2Y4MWU0NWM3NDAzZGIxZGVlYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iRyHgCTB1aSuSQDXxYuYbmeBZ_Uiu0knUWiSh1K_Ip0) 有晓梦这个人吗？


具体支持的声音可以在 [这里查询](https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/list?trustedclienttoken=6A5AA1D4EAFF4E9FB37E23D68491D6F4)  ,我看了一下，没有看到晓梦。  

目前支持的中文语音如下
```
zh-HK-HiuGaaiNeural
zh-HK-HiuMaanNeural
zh-HK-WanLungNeural
zh-CN-XiaoxiaoNeural
zh-CN-XiaoyiNeural
zh-CN-YunjianNeural
zh-CN-YunxiNeural
zh-CN-YunxiaNeural
zh-CN-YunyangNeural
zh-CN-liaoning-XiaobeiNeural
zh-TW-HsiaoChenNeural
zh-TW-YunJheNeural
zh-TW-HsiaoYuNeural
zh-CN-shaanxi-XiaoniNeural
```
可能服务本身是有这个声音的，但是本项目使用的账户凭证下不支持这个声音
