### ISSUE TITLE
国内不能使用

### ISSUE THREAD

**Issue by tjglfglf** [WhiteMagic2014/tts-edge-java#7]
今天突然发现不能使用了，尝试使用代理ip后可以访问，是不是限制国内访问了

**Comment by tjglfglf** [comment]
不清楚是国内的问题还是限制了访问频次

**Comment by WhiteMagic2014** [comment]
这个本质上还是使用的还是edge的服务，如果出现无法访问的情况，建议更换网络环境后再次尝试

**Comment by RXlung** [comment]
这个库是不是彻底失效了。 不论是切换其他无线网络还是流量热点还是不同的发声人，都没法回调出来。

**Comment by WhiteMagic2014** [comment]
> 这个库是不是彻底失效了。 不论是切换其他无线网络还是流量热点还是不同的发声人，都没法回调出来。 另外，感谢大佬的开源，断断续续也是使用了一个月。

我刚刚测试了一下，库本身还是可以用的，但好像是屏蔽了国内的访问。不挂代理我也没法调用成功，挂上代理后又一切正常。
简单需要用这个功能的话，[点击这里可以在线使用](https://server.whitemagic2014.com/tts/) 
如果需要开发自己的应用，部署使用，建议把服务器放在国外

**Comment by WhiteMagic2014** [comment]
可以过一段时间再看看，是不是还屏蔽国内的访问

**Comment by WhiteMagic2014** [comment]
更新版本1.2.5. 其中有参数 isRateLimited。 如果在国内用不了 设置为true即可

**Comment by WhiteMagic2014** [comment]
> 这个库是不是彻底失效了。 不论是切换其他无线网络还是流量热点还是不同的发声人，都没法回调出来。 另外，感谢大佬的开源，断断续续也是使用了一个月。

更新版本1.2.5. 其中有参数 isRateLimited。 如果在国内用不了 设置为true即可
